# Generated by Django 4.2.16 on 2024-11-01 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("character_name", models.CharField(max_length=100, unique=True)),
                ("profession", models.CharField(max_length=50)),
                ("role", models.CharField(max_length=50)),
                ("specialization", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="DKPLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.IntegerField()),
                (
                    "action_type",
                    models.CharField(
                        choices=[("add", "增加"), ("remove", "减少")], max_length=10
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dkp_management.player",
                    ),
                ),
            ],
        ),
    ]
