# Generated by Django 4.2.16 on 2024-11-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dkp_management", "0004_player_total_dkp_alter_dkplog_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="profession",
            field=models.CharField(
                choices=[
                    ("Death Knight", "死亡骑士"),
                    ("Demon Hunter", "恶魔猎手"),
                    ("Druid", "德鲁伊"),
                    ("Evoker", "唤魔师"),
                    ("Hunter", "猎人"),
                    ("Mage", "法师"),
                    ("Monk", "武僧"),
                    ("Paladin", "圣骑士"),
                    ("Priest", "牧师"),
                    ("Rogue", "潜行者"),
                    ("Shaman", "萨满"),
                    ("Warlock", "术士"),
                    ("Warrior", "战士"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="role",
            field=models.CharField(
                choices=[("Tank", "坦克"), ("Healer", "治疗"), ("DPS", "输出")],
                max_length=50,
            ),
        ),
    ]
