# Generated by Django 4.2.16 on 2024-11-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dkp_management", "0005_alter_player_profession_alter_player_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("points", models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="player",
            name="specialization",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
